version: 2

models:
  - name: stg_clean_data
    description: "A staging model that will clean the healthcare dataset."
    columns:
      - name: patient_id
        description: "The primary key for this table."
        data_tests:
          - unique
          - not_null

  - name: tr_data_aggregations
    description: "Aggregated metrics from the healthcare dataset."
    columns:
      - name: patient_gender
        description: "Gender of the patient."
        data_tests:
          - not_null
          - accepted_values:
              values: ['Male', 'Female']
      - name: length_of_stay_days
        description: "Number of days the patient stayed in the hospital."
        data_tests:
          - not_null
          - custom_test:
              name: LOS_greater_than_zero
              args:
                column: length_of_stay_days
      - name: patient_count
        description: "Count of patients by gender."
        data_tests:
          - not_null
          - relationships:
              to: ref('stg_healthcare_rename')
              field: patient_gender
      - name: average_billing_amount
        description: "Average billing amount for each medical condition."
        data_tests:
          - not_null
          - custom_test:
              name: avg_bill_nonnegative
              args:
                column: average_billing_amount
      - name: total_admissions
        description: "Total number of admissions by hospital."
        data_tests:
          - not_null
          - custom_test:
              name: tot_admission_nonnegative
              args:
                column: total_admissions
      - name: average_length_of_stay
        description: "Average length of stay by admission type."
        data_tests:
          - not_null
          - custom_test:
              name: avg_LOS_nonnegative
              args:
                column: average_length_of_stay
